//! Where Part III's prediction meets Part I's measurement.
//!
//! These tests live in the CLI crate because it is the only one that depends on both the
//! closure engine and the instruments. They check the two arrows of Part III 2 that can be
//! checked against a running circuit -- `rank(QFIM) <= dim(g)` and the loss variance -- and
//! they check the case where the prediction does *not* apply, which matters more.

use overtone_lie::family::{self, EntanglerPolicy};
use overtone_lie::{closure_unbounded, PauliString, Prediction};
use overtone_rl::{Scaling, SpectralControlAnsatz};
use overtone_spec::qfim::{qfim, rank};

fn params_for(len: usize, seed: u64) -> Vec<f64> {
    let mut s = seed;
    (0..len)
        .map(|_| {
            s = s
                .wrapping_mul(6364136223846793005)
                .wrapping_add(1442695040888963407);
            ((s >> 11) as f64 / (1u64 << 53) as f64) * 2.0 * std::f64::consts::PI
                - std::f64::consts::PI
        })
        .collect()
}

#[test]
fn the_fisher_rank_never_exceeds_the_dimension_of_the_algebra() {
    // The circuit's unitary lies in the group generated by *every* gate's generator, fixed
    // entanglers included, so that is the algebra the bound is stated against.
    for qubits in 2..=4 {
        for layers in 1..=3 {
            let ansatz = SpectralControlAnsatz::build(qubits, layers, Scaling::Pinned, true);
            let circuit = ansatz.build(&[0.7]);
            let extracted = family::from_circuit(&circuit, EntanglerPolicy::Parameterised);
            let dim_g = closure_unbounded(&extracted.generators, qubits).dim();

            let p = ansatz.num_params();
            let params = params_for(p, 11 + qubits as u64 * 10 + layers as u64);
            let f = qfim(&circuit, &params);
            let r = rank(&f, p, 1e-9);
            assert!(
                r <= dim_g,
                "n={qubits} L={layers}: rank(QFIM) = {r} exceeded dim(g) = {dim_g}"
            );
        }
    }
}

#[test]
fn a_fixed_entangler_ansatz_escapes_the_algebra_of_its_trainable_generators() {
    // The Part I ansatz has only single-qubit trainable rotations, so the strict DLA is
    // su(2)^(+n) of dimension 3n. If that algebra described the circuit, the Fisher rank
    // could not exceed it. It does -- which is the whole reason `Prediction` refuses to
    // make a trainability claim when fixed entanglers are present.
    let qubits = 3;
    let layers = 4;
    let ansatz = SpectralControlAnsatz::build(qubits, layers, Scaling::Pinned, true);
    let circuit = ansatz.build(&[0.7]);

    let strict = family::from_circuit(&circuit, EntanglerPolicy::Strict);
    assert!(
        strict.fixed_entanglers > 0,
        "the ansatz should have CZ layers"
    );
    let dim_strict = closure_unbounded(&strict.generators, qubits).dim();
    assert_eq!(dim_strict, 3 * qubits, "strict DLA should be su(2)^(+n)");

    let p = ansatz.num_params();
    let params = params_for(p, 4242);
    let r = rank(&qfim(&circuit, &params), p, 1e-9);
    assert!(
        r > dim_strict,
        "Fisher rank {r} did not exceed the strict dim(g) {dim_strict}, so this test no \
         longer demonstrates anything"
    );

    let mut report = Prediction::new(
        &closure_unbounded(&strict.generators, qubits),
        &PauliString::single(0, overtone_sim::Pauli::Z),
    );
    report.note_fixed_entanglers(strict.fixed_entanglers);
    assert!(report.leaves_the_group);
    assert!(report.verdict().contains("No trainability claim follows"));
}

#[test]
fn the_ansatz_with_trainable_entanglers_is_all_of_su() {
    for qubits in 2..=4 {
        let ansatz = SpectralControlAnsatz::build(qubits, 2, Scaling::Pinned, true);
        let circuit = ansatz.build(&[0.7]);
        let extracted = family::from_circuit(&circuit, EntanglerPolicy::Parameterised);
        let dim_g = closure_unbounded(&extracted.generators, qubits).dim();
        assert_eq!(dim_g, (1usize << (2 * qubits)) - 1, "n = {qubits}");
    }
}
