// Overtone. Copyright (C) 2026 Anbuchelvan Ganesan.
// Licensed under the GNU Affero General Public License, version 3 or (at your option) any
// later version. See LICENSE, or <https://www.gnu.org/licenses/>. This program is
// distributed WITHOUT ANY WARRANTY; see the licence for details.

//! `.otn` — the notation, frozen and versioned.
//!
//! Part VIII 1: "This format is the actual deliverable of Part VIII. Everything after it is
//! convenience." Part VIII 11: "Do not let the notation drift. Freeze early, version
//! explicitly." So this crate is small, its format is pinned by [`FORMAT_VERSION`], and its
//! tests are mostly about round-tripping rather than about physics.
//!
//! # What was learned from PGN and FEN before a byte was written
//!
//! Part VIII 12 says to read them first: "they are unusually well-designed and forty years of
//! use has tested them." Four decisions were taken straight from them.
//!
//! **A mandatory header roster, and free extension around it.** PGN has the Seven Tag Roster:
//! "the STR is the common ground that all programs should follow for public data
//! interchange", while "the definition and use of additional tag names and semantics is
//! permitted and encouraged when needed". [`REQUIRED`] is the same idea, and [`Record::extra`]
//! is where anything else goes, preserved on round-trip.
//!
//! **Import format versus export format.** PGN accepts loosely-typed input but requires that
//! "export format representations generated by different PGN programs on the same computing
//! system should be exactly equivalent, byte for byte". [`parse`] is permissive; [`Record::to_otn`]
//! is byte-exact and canonical, and `tests/roundtrip.rs` pins both directions.
//!
//! **An escape for private data.** PGN reserves a leading `%` for "the private use of software
//! developers and researchers to embed non-PGN commands and data in PGN streams". `.otn`
//! keeps the same character and the same meaning: a `%` line is ignored by the parser and is
//! not required to survive a round trip.
//!
//! **Record what the engine needs to resume, not what a reader could infer.** This is FEN's
//! lesson — its halfmove clock and fullmove number exist because a machine cannot infer the
//! fifty-move rule from a diagram, while a human reader could. A `.otn` position is therefore
//! a *seed plus a move list*, not a dump of the amplitude field: the engine is deterministic,
//! so the moves are the position, and a few hundred bytes replace `2^n` complex numbers.
//!
//! # Two traps this format had to design around
//!
//! **`DefaultHasher` cannot back a self-verifying format.** Part VIII 1 requires the file to
//! carry a hash of the final state so that "re-running is a proof". Rust's
//! `std::collections::hash_map::DefaultHasher` is explicitly not guaranteed stable across
//! releases, so a hash written by one toolchain would fail to verify under another. [`fnv1a`]
//! is written out here for that reason.
//!
//! **Hashing raw `f64` bits would make the proof platform-dependent.** This repository's own
//! `wasm_determinism.sh` measures native-versus-wasm agreement at a worst relative difference
//! of about `5.6e-16` — agreement to a tolerance, not bit-for-bit equality. A hash over raw
//! bits would therefore disagree between a native run and a browser run of the same game,
//! which is exactly the case the hash exists to check. Amplitudes are quantised to
//! [`HASH_QUANTUM`] first, which is far coarser than the measured divergence and far finer
//! than anything physically meaningful.

#![forbid(unsafe_code)]

pub mod hash;
pub mod parse;
pub mod puzzle;
pub mod record;

pub use hash::{fnv1a, state_hash, HASH_QUANTUM};
pub use parse::{parse, ParseError};
pub use puzzle::{balance, overtone_100, verify, Answer, Kind, Puzzle, SET_SIZE};
pub use record::{Ply, Record, Result_, FORMAT_VERSION, REQUIRED, RULESET};
