//! Emit differential-test cases for the Yao.jl oracle.
//!
//! Writes a line-oriented description of randomly generated circuits together with the
//! expectation value and adjoint gradient this crate computes for each. `lab/test/oracle.jl`
//! reconstructs the circuits in Yao.jl and checks the numbers independently.
//!
//! Run with:
//!
//! ```text
//! cargo run -p overtone-sim --example emit_oracle_cases > lab/test/cases.txt
//! ```
//!
//! The format is deliberately plain text rather than JSON so that neither side needs a
//! serialisation dependency. Floats are written with full `f64` precision.

use overtone_sim::gate::{Angle, Gate};
use overtone_sim::grad::adjoint;
use overtone_sim::random::{random_circuit, random_params, RandomCircuitOpts};
use overtone_sim::{Circuit, Observable};

fn f(x: f64) -> String {
    format!("{x:.17e}")
}

fn emit_case(id: usize, circuit: &Circuit, params: &[f64], obs: &Observable, obs_tag: &str) {
    let vg = adjoint::value_and_grad(circuit, params, obs);

    println!(
        "CASE {id} {} {} {}",
        circuit.num_qubits(),
        params.len(),
        circuit.len()
    );
    println!(
        "PARAMS {}",
        params.iter().map(|p| f(*p)).collect::<Vec<_>>().join(" ")
    );

    for gate in circuit.gates() {
        match gate {
            Gate::Rx { q, angle } | Gate::Ry { q, angle } | Gate::Rz { q, angle } => {
                let kind = match gate {
                    Gate::Rx { .. } => "RX",
                    Gate::Ry { .. } => "RY",
                    _ => "RZ",
                };
                match angle {
                    Angle::Param { index, scale } => {
                        println!("G {kind} {q} P {index} {}", f(*scale))
                    }
                    Angle::Fixed(t) => println!("G {kind} {q} F {}", f(*t)),
                }
            }
            Gate::H { q } => println!("G H {q}"),
            Gate::Cz { a, b } => println!("G CZ {a} {b}"),
            Gate::Cnot { control, target } => println!("G CX {control} {target}"),
            Gate::U { .. } => unreachable!("the oracle generator does not emit raw unitaries"),
        }
    }

    println!("OBS {obs_tag}");
    println!("VALUE {}", f(vg.value));
    println!(
        "GRAD {}",
        vg.grad.iter().map(|g| f(*g)).collect::<Vec<_>>().join(" ")
    );
    println!("ENDCASE");
}

fn main() {
    println!("# overtone-sim oracle cases");
    println!("# generated by crates/overtone-sim/examples/emit_oracle_cases.rs");

    let mut id = 0;
    for n in 1..=4usize {
        for depth in 1..=3usize {
            for seed in 0..4u64 {
                let opts = RandomCircuitOpts {
                    num_qubits: n,
                    depth,
                    entangle: n > 1,
                    // Both of these are on: the oracle checks the chain rule and the
                    // accumulation across gates that share a parameter, not just the
                    // easy unit-scale case.
                    scaled_angles: true,
                    share_params: true,
                };
                let c = random_circuit(seed, opts);
                let p = random_params(seed ^ 0xC0FFEE_u64, c.num_params());

                emit_case(id, &c, &p, &Observable::z(0), "Z0");
                id += 1;
                emit_case(id, &c, &p, &Observable::z_global(n), "ZALL");
                id += 1;
            }
        }
    }
}
