//! Generating sets: the standard spin-chain families, and extraction from a circuit.
//!
//! The families are the ones tabulated in Wiersema, Kokcu, Kemper and Bakalov,
//! *Classification of dynamical Lie algebras of 2-local spin systems*, npj Quantum
//! Information 10 (2024), arXiv:2309.05690. Their labels `a_k` are kept in the doc comments
//! so the unit tests in `tests/published_dimensions.rs` can be read against the paper.

use overtone_sim::{Circuit, Gate, Pauli};

use crate::pauli::PauliString;

fn two_site(n: usize, a: Pauli, b: Pauli, periodic: bool) -> Vec<PauliString> {
    let last = if periodic { n } else { n - 1 };
    (0..last)
        .map(|i| PauliString::from_factors(&[(i, a), ((i + 1) % n, b)]))
        .collect()
}

fn one_site(n: usize, a: Pauli) -> Vec<PauliString> {
    (0..n).map(|i| PauliString::single(i, a)).collect()
}

/// Transverse-field Ising: `{Z_i Z_{i+1}} u {X_i}`, open chain.
///
/// Wiersema et al. Example II.1. Its algebra is `so(2n)`, dimension `n(2n - 1)` — the
/// canonical polynomial DLA, and the one the 100-qubit g-sim run of Part III 4 uses.
pub fn tfim(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::Z, Pauli::Z, false);
    g.extend(one_site(n, Pauli::X));
    g
}

/// Transverse-field Ising on a ring: `so(2n) (+) so(2n)`.
pub fn tfim_ring(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::Z, Pauli::Z, true);
    g.extend(one_site(n, Pauli::X));
    g
}

/// Heisenberg chain `{XX, YY, ZZ}`, open. Wiersema et al. `a_7`: exponential.
pub fn heisenberg(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::X, Pauli::X, false);
    g.extend(two_site(n, Pauli::Y, Pauli::Y, false));
    g.extend(two_site(n, Pauli::Z, Pauli::Z, false));
    g
}

/// Ising coupling alone `{XX}`. Wiersema et al. `a_0`: abelian, dimension `n - 1`.
pub fn ising(n: usize) -> Vec<PauliString> {
    two_site(n, Pauli::X, Pauli::X, false)
}

/// Kitaev chain `{XY}`. Wiersema et al. `a_1`: `so(n)`.
pub fn kitaev(n: usize) -> Vec<PauliString> {
    two_site(n, Pauli::X, Pauli::Y, false)
}

/// XY model `{XX, YY}`. Wiersema et al. `a_4`: `so(n) (+) so(n)`.
pub fn xy(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::X, Pauli::X, false);
    g.extend(two_site(n, Pauli::Y, Pauli::Y, false));
    g
}

/// `{XX, XZ}`. Wiersema et al. `a_8`: `so(2n - 1)`.
pub fn a8(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::X, Pauli::X, false);
    g.extend(two_site(n, Pauli::X, Pauli::Z, false));
    g
}

/// `{XY, XZ}`. Wiersema et al. `a_9`: `sp(2^(n-2))`.
pub fn a9(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::X, Pauli::Y, false);
    g.extend(two_site(n, Pauli::X, Pauli::Z, false));
    g
}

/// `{XY, YX, YZ}`. Wiersema et al. `a_11`: `so(2^n)`.
pub fn a11(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::X, Pauli::Y, false);
    g.extend(two_site(n, Pauli::Y, Pauli::X, false));
    g.extend(two_site(n, Pauli::Y, Pauli::Z, false));
    g
}

/// `{XX, YY, XY}`. Wiersema et al. `a_14`: `so(2n)`, the same class as the TFIM.
pub fn a14(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::X, Pauli::X, false);
    g.extend(two_site(n, Pauli::Y, Pauli::Y, false));
    g.extend(two_site(n, Pauli::X, Pauli::Y, false));
    g
}

/// `{XX, XY, XZ}`. Wiersema et al. `a_15`: `su(2^(n-1)) (+) su(2^(n-1))`.
pub fn a15(n: usize) -> Vec<PauliString> {
    let mut g = two_site(n, Pauli::X, Pauli::X, false);
    g.extend(two_site(n, Pauli::X, Pauli::Y, false));
    g.extend(two_site(n, Pauli::X, Pauli::Z, false));
    g
}

/// A hardware-efficient ansatz with **trainable** entanglers: `{X_i, Y_i, Z_i Z_{i+1}}`.
/// The algebra is all of `su(2^n)`, dimension `4^n - 1`.
pub fn hardware_efficient(n: usize) -> Vec<PauliString> {
    let mut g = one_site(n, Pauli::X);
    g.extend(one_site(n, Pauli::Y));
    g.extend(two_site(n, Pauli::Z, Pauli::Z, false));
    g
}

/// Uncoupled single-qubit rotations: `su(2)^(+n)`, dimension `3n`.
///
/// This is what a hardware-efficient ansatz reduces to when its entanglers are *fixed*
/// Cliffords, which is how Part I 6.2 actually builds one — see [`EntanglerPolicy`].
pub fn single_qubit_only(n: usize) -> Vec<PauliString> {
    let mut g = one_site(n, Pauli::X);
    g.extend(one_site(n, Pauli::Y));
    g
}

/// How to treat a circuit's fixed entangling gates when extracting generators.
///
/// The dynamical Lie algebra is generated by the generators of the **parameterised** gates.
/// A fixed CZ layer is not a one-parameter subgroup; it conjugates the algebra rather than
/// extending it. That distinction is usually elided in informal statements like "the
/// hardware-efficient ansatz has DLA `su(2^n)`", which is true of parameterised entanglers
/// and false of fixed ones, and the difference is `4^n - 1` against `3n`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum EntanglerPolicy {
    /// Strict: only parameterised gates contribute. Fixed entanglers are reported as a
    /// caveat, because Ragone et al.'s Theorem 1 then does not apply to the circuit — its
    /// unitary is not in `exp(g)`.
    Strict,
    /// Treat every entangler as though its angle were free. This is the algebra people
    /// usually mean when they name an ansatz, and it is an upper bound on the strict one.
    Parameterised,
}

/// What a circuit contributes to the closure.
pub struct CircuitGenerators {
    pub generators: Vec<PauliString>,
    /// Fixed entangling gates that were skipped under [`EntanglerPolicy::Strict`].
    pub fixed_entanglers: usize,
    /// Fixed non-entangling gates (H, fixed rotations). These conjugate too, but within
    /// one qubit, so they are far less likely to be load-bearing.
    pub fixed_local: usize,
}

/// Extract generators from a circuit.
pub fn from_circuit(circuit: &Circuit, policy: EntanglerPolicy) -> CircuitGenerators {
    let mut generators = Vec::new();
    let mut fixed_entanglers = 0;
    let mut fixed_local = 0;
    let mut push = |p: PauliString| {
        if !generators.contains(&p) {
            generators.push(p);
        }
    };
    for gate in circuit.gates() {
        match gate {
            Gate::Rx { q, angle } => {
                if angle.param_ref().is_some() {
                    push(PauliString::single(*q, Pauli::X));
                } else {
                    fixed_local += 1;
                }
            }
            Gate::Ry { q, angle } => {
                if angle.param_ref().is_some() {
                    push(PauliString::single(*q, Pauli::Y));
                } else {
                    fixed_local += 1;
                }
            }
            Gate::Rz { q, angle } => {
                if angle.param_ref().is_some() {
                    push(PauliString::single(*q, Pauli::Z));
                } else {
                    fixed_local += 1;
                }
            }
            Gate::H { .. } | Gate::U { .. } => fixed_local += 1,
            Gate::Cz { a, b } => match policy {
                EntanglerPolicy::Strict => fixed_entanglers += 1,
                EntanglerPolicy::Parameterised => {
                    push(PauliString::from_factors(&[(*a, Pauli::Z), (*b, Pauli::Z)]))
                }
            },
            Gate::Cnot { control, target } => match policy {
                EntanglerPolicy::Strict => fixed_entanglers += 1,
                EntanglerPolicy::Parameterised => push(PauliString::from_factors(&[
                    (*control, Pauli::Z),
                    (*target, Pauli::X),
                ])),
            },
        }
    }
    CircuitGenerators {
        generators,
        fixed_entanglers,
        fixed_local,
    }
}
