//! M41's acceptance: the format round-trips, and it stays frozen.

use overtone_orbit::game::{Move, Piece};
use overtone_otn::{fnv1a, parse, ParseError, Ply, Record, Result_, FORMAT_VERSION, REQUIRED};

fn sample() -> Record {
    let mut r = Record::new(4, 24, 2, 7);
    r.engine = "overtone 0.1.0".to_string();
    r.plies = vec![
        Ply {
            mv: Move::Apply {
                piece: Piece::Pawn,
                targets: vec![0],
            },
            angle: 4,
        },
        Ply {
            mv: Move::Apply {
                piece: Piece::Rook,
                targets: vec![3],
            },
            angle: 8,
        },
        Ply {
            mv: Move::Apply {
                piece: Piece::Bishop,
                targets: vec![0, 1],
            },
            angle: 2,
        },
        Ply {
            mv: Move::Apply {
                piece: Piece::Knight,
                targets: vec![2, 3],
            },
            angle: 6,
        },
        Ply {
            mv: Move::Measure { qubit: 1 },
            angle: 0,
        },
    ];
    r.result = Result_::Checkmate(1);
    r.hash = Some(0xdead_beef_0000_0001);
    r.extra.insert("Event".into(), "Overtone-100".into());
    r
}

#[test]
fn a_record_survives_a_round_trip() {
    let r = sample();
    let text = r.to_otn();
    let back = parse(&text).expect("parses");
    assert_eq!(r, back);
}

#[test]
fn export_format_is_byte_exact() {
    // PGN: "export format representations generated by different PGN programs on the same
    // computing system should be exactly equivalent, byte for byte." Writing what was read
    // must therefore be a fixed point, not merely equivalent.
    let text = sample().to_otn();
    let once = parse(&text).unwrap().to_otn();
    let twice = parse(&once).unwrap().to_otn();
    assert_eq!(text, once);
    assert_eq!(once, twice);
}

#[test]
fn the_import_format_is_permissive() {
    // Everything below is legal input and must produce the same record as the canonical form.
    let messy = r#"
% a private escape line the parser must ignore entirely
; a comment

[Event "Overtone-100"]
[Otn "1"]
   [Engine   "overtone 0.1.0"]
[Ruleset "vii.7"]
[Qubits "4"]   ; trailing comment
[Coherence "24"]
[K "2"]
[Seed "7"]
[Hash "deadbeef00000001"]
[Result "checkmate/1"]

1. P0/4 R3/8   { an inline comment }
2. B0-1/2
   N2-3/6
3. M1
"#;
    assert_eq!(parse(messy).unwrap(), sample());
}

#[test]
fn every_roster_tag_is_required() {
    let text = sample().to_otn();
    for tag in REQUIRED {
        let stripped: String = text
            .lines()
            .filter(|l| !l.starts_with(&format!("[{tag} ")))
            .collect::<Vec<_>>()
            .join("\n");
        assert_eq!(
            parse(&stripped),
            Err(ParseError::MissingTag(tag.to_string())),
            "dropping [{tag}] should be an error"
        );
    }
}

#[test]
fn a_future_version_is_refused_rather_than_guessed() {
    // Part VIII 9: physics drift breaks old replays. A reader that guessed would produce a
    // wrong game silently, which is worse than refusing.
    let text = sample().to_otn().replace("[Otn \"1\"]", "[Otn \"2\"]");
    assert!(matches!(parse(&text), Err(ParseError::UnknownVersion(_))));
    let text = sample().to_otn().replace("vii.7", "vii.8");
    assert!(matches!(parse(&text), Err(ParseError::WrongRuleset(_))));
}

#[test]
fn move_numbers_are_decoration() {
    // They are re-derived on output, so a parser must not trust them to sequence the game.
    let good = sample().to_otn();
    let lied = good.replace("2. ", "97. ").replace("3. ", "1. ");
    assert_eq!(parse(&lied).unwrap().plies, sample().plies);
}

#[test]
fn every_ply_token_round_trips() {
    for piece in Piece::ALL {
        let targets: Vec<usize> = (0..piece.arity()).collect();
        for angle in 1..=8 {
            let p = Ply {
                mv: Move::Apply {
                    piece,
                    targets: targets.clone(),
                },
                angle,
            };
            assert_eq!(
                Ply::from_token(&p.token()),
                Some(p.clone()),
                "{}",
                p.token()
            );
        }
    }
    for qubit in 0..6 {
        let p = Ply {
            mv: Move::Measure { qubit },
            angle: 0,
        };
        assert_eq!(Ply::from_token(&p.token()), Some(p));
    }
}

#[test]
fn bad_ply_tokens_are_rejected() {
    for bad in [
        "P0/0", "P0/9", "B0/2", "P0-1/2", "X0/2", "P/2", "Pq0/2", "M", "1.2",
    ] {
        assert!(Ply::from_token(bad).is_none(), "{bad:?} should not parse");
    }
}

#[test]
fn extra_tags_survive_but_do_not_displace_the_roster() {
    let mut r = sample();
    r.extra.insert("Zulu".into(), "last".into());
    r.extra.insert("Alpha".into(), "first".into());
    let text = r.to_otn();
    assert_eq!(parse(&text).unwrap(), r);
    // The roster comes first, in roster order; extras follow in ASCII order.
    let tag_lines: Vec<&str> = text.lines().filter(|l| l.starts_with('[')).collect();
    for (i, tag) in REQUIRED.iter().enumerate() {
        assert!(
            tag_lines[i].starts_with(&format!("[{tag} ")),
            "roster order at {i}"
        );
    }
    let alpha = tag_lines
        .iter()
        .position(|l| l.starts_with("[Alpha "))
        .unwrap();
    let event = tag_lines
        .iter()
        .position(|l| l.starts_with("[Event "))
        .unwrap();
    let zulu = tag_lines
        .iter()
        .position(|l| l.starts_with("[Zulu "))
        .unwrap();
    assert!(
        alpha < event && event < zulu,
        "extras must be in ASCII order"
    );
}

#[test]
fn a_whole_game_is_a_few_hundred_bytes() {
    // Part VIII 1: "A few hundred bytes for a whole game."
    let mut r = Record::new(4, 24, 2, 3);
    for i in 0..60 {
        r.plies.push(Ply {
            mv: Move::Apply {
                piece: Piece::ALL[i % 4],
                targets: (0..Piece::ALL[i % 4].arity()).collect(),
            },
            angle: (i % 8) + 1,
        });
    }
    r.result = Result_::Exhausted;
    r.hash = Some(1);
    let n = r.to_otn().len();
    assert!(n < 900, "a 60-ply game serialised to {n} bytes");
}

#[test]
fn the_hash_is_stable_and_not_the_standard_library_hasher() {
    // Pinned literals, cross-checked against an independent implementation of FNV-1a rather
    // than against this one. If they ever change, every published record stops verifying, so
    // the change has to be deliberate enough to edit this test.
    assert_eq!(fnv1a(b""), 0xcbf2_9ce4_8422_2325, "the FNV offset basis");
    assert_eq!(fnv1a(b"overtone"), 0x8e1b_756d_7974_6b0b);
    assert_eq!(FORMAT_VERSION, 1);
}
